CREATE TABLE budget
(
    id     INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    year   INT NOT NULL,
    month  INT NOT NULL,
    amount INT NOT NULL,
    type   VARCHAR(50) NOT NULL,
    author_id INT REFERENCES author(id)
);